spring:
  application:
    name: spotify-feeder

couchbase:
  bucket-name: Song
  password: cbpassword
  connection-string: localhost
  username: Administrator

server:
  port: 8099
  shutdown: graceful
  compression:
    enabled: true
  http2:
    enabled: true
